import { db } from "../firebase-connection";
import { ProfitPerLot } from "../../domain/ProfitPerLot";
import { collection, doc, getDoc, addDoc, updateDoc, deleteDoc, getDocs } from "firebase/firestore";

// Function to add a new ProfitPerLot record
export async function addProfitPerLot(data) {
    const newProfitPerLot = new ProfitPerLot(
        null, // ID will be auto-generated by Firestore
        data.cost,
        data.id_product,
        data.profit,
        data.total_sell
    );
    const docRef = await addDoc(collection(db, "profits_per_lot"), newProfitPerLot.toFirestore());
    return docRef.id; // Return the new document ID
}

// Function to get a ProfitPerLot by ID
export async function getProfitPerLotById(id) {
    const docRef = doc(db, "profits_per_lot", id);
    const docSnap = await getDoc(docRef);

    if (!docSnap.exists()) {
        throw new Error("No such profit per lot found");
    }

    const data = docSnap.data();
    return new ProfitPerLot(docSnap.id, data.cost, data.id_product, data.profit, data.total_sell);
}

// Function to update a ProfitPerLot record
export async function updateProfitPerLot(id, newData) {
    const profitPerLotRef = doc(db, "profits_per_lot", id);
    await updateDoc(profitPerLotRef, newData);
    return `ProfitPerLot with ID ${id} updated successfully.`;
}

// Function to delete a ProfitPerLot record
export async function deleteProfitPerLot(id) {
    const profitPerLotRef = doc(db, "profits_per_lot", id);
    await deleteDoc(profitPerLotRef);
    return `ProfitPerLot with ID ${id} deleted successfully.`;
}

// Function to fetch all ProfitPerLot records
export async function getAllProfitPerLot() {
    const collectionRef = collection(db, "profits_per_lot");
    const snapshot = await getDocs(collectionRef);
    const profitList = [];
    snapshot.forEach(doc => {
        const data = doc.data();
        profitList.push(new ProfitPerLot(doc.id, data.cost, data.id_product, data.profit, data.total_sell));
    });
    return profitList;
}

export default {
    addProfitPerLot,
    getProfitPerLotById,
    updateProfitPerLot,
    deleteProfitPerLot,
    getAllProfitPerLot
};
